### ISSUE TITLE
Prompt for new project type selection duplicates options on arrow key press

### ISSUE THREAD

**Issue by cybairfly** [apify/apify-cli#102]
Prompt triggered by `apify create *` keeps attaching all the option lines when arrow keys are pressed on apify-cli@latest and latest npm in Windows 7 terminal. Current option is always correctly highlighted in the options added last but other options are stuck as highlighted in the previous option lists. Nevertheless, the command execution still does work.

**Comment by mtrunkat** [comment]
Old, reopen if somebody replicates the issue on Windows
