### ISSUE TITLE
Cannot push on Apify

### ISSUE THREAD

**Issue by tugkan** [apify/apify-cli#132]
When I try to execute `apify push` command it creates an empty actor on the platform but gives me an error.  Here are some information about the settings that I use;

**Versions:**
```
OS: OSX 10.15 Catalina
NodeJS:  8.14.0
```

**apify.json**
```
{
    "name": "test-actor",
    "version": "1.0",
    "buildTag": "latest",
    "env": {
        "APIFY_MEMORY_MBYTES": 4096
    },
    "template": "puppeteer_crawler"
}
```

**Output Error:**
```
{ id: 'XXXXXXXX',
  userId: 'XXXXXX',
  name: 'test-actor',
  username: 'tugkan',
  restartOnError: false,
  isPublic: false,
  isAnonymouslyRunnable: false,
  createdAt: 2019-10-10T11:26:39.923Z,
  modifiedAt: 2019-10-10T11:26:39.923Z,
  stats:
   { totalBuilds: 0,
     totalRuns: 0,
     totalUsers: 1,
     totalUsers7Days: 0,
     totalUsers30Days: 0,
     totalUsers90Days: 0 },
  versions:
   [ { versionNumber: '1.0',
       buildTag: 'latest',
       sourceType: 'TARBALL',
       envVars: [] } ],
  defaultRunOptions: { build: 'latest', timeoutSecs: 0, memoryMbytes: 2048 },
  exampleRunInput:
   { body: '{ "helloWorld": 123 }',
     contentType: 'application/json; charset=utf-8' },
  isDeprecated: false }
Info: Deploying actor 'test-actor' to Apify.
Error: Invalid value provided: Value must be a string
```

**Comment by drobnikj** [comment]
Hi @tugkan,

it looks problem is with your `env` value in apify.json.
An environment variable can be just string and you had there int.
`"APIFY_MEMORY_MBYTES": 4096`

There is bad error message which we need to fix.

Anyway if you want to change memory for actor runs you need to change it in UI. Actor -> Settings -> Default run options.
But it would be great to have an option to set it with `apify push` command -> #133

**Comment by tugkan** [comment]
That fixed it. If that's the case then I think `apify vis` should validate string/integer values as well. Am I right?

**Comment by drobnikj** [comment]
@tugkan not really. Command `apify vis` works just with INPUT_SCHEMA.json.

**Comment by drobnikj** [comment]
The error was improve on platform and it is propagated into CLI.
