### ISSUE TITLE
[feature] apify run --docker

### ISSUE THREAD

**Issue by pocesar** [apify/apify-cli#141]
If `--docker` is provided, start it in Docker daemon using the `Dockerfile` instead. this would diminish cross platform issues (like Windows / Linux / BSD) and would closely be able to mimic the platform (and take `apify login` into account as well).

**Comment by drobnikj** [comment]
Thanks for this feature request @pocesar !

It is a good idea to have it there, do you have any use case, where is it useful?
It will be helpful to set up a priority for this feature.

**Comment by pocesar** [comment]
hey @drobnikj, yes, for example, when using containerUrl and containerPort locally, those are null, and they are only available on the platform. this is mainly useful when you need to bind to the container port and have access to something internally, but from the outside. 
I think it shouldn't be a 1:1 emulation, but would be nice to be able to test the container behavior before deploying/pushing. there's no rush though 😄

**Comment by mtrunkat** [comment]
Closing for now, reopen if needed
