### ISSUE TITLE
Deploying using git repo ignores version set inside apify.json

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-cli#159]
Moved from https://github.com/apifytech/apify-js/issues/563 @pocesar

When using `apify push`, the platform sets the "build" to the correct version (`0.0` -> `0.1`). when doing the same using git, the build is always `0.0`, regardless of version set inside `apify.json` and `package.json` (bumped both to see if would make a difference)

**Comment by drobnikj** [comment]
Hey @pocesar,

thanks for the issue. File apify.json was made mainly for apify CLI purposes. 
But you are right that it will make sense to use it on a platform as well. Especially for new version, where you build actor from a git repository.
But this function needs to be done on Apify platform. I added this issue on the [Apify product roadmap](https://portal.productboard.com/apify/).
