### ISSUE TITLE
[feature] Specify configuration file when using "apify push"

### ISSUE THREAD

**Issue by remyoucef** [apify/apify-cli#160]
Currently `apify push` use  **apify.json** file when building the actor, it would be nice if we add an option to specify this file. We can use that for separating development actor (e.g. _apify.dev.json_) from production actor (e.g. _apify.json_).

**Comment by drobnikj** [comment]
You can override some variables from apify.json using push tags already:
-build-tag - Build tag to be applied to the successful actor build. By default, it is taken from the "apify.json" file
-version -Actor version number to which the files should be pushed. By default, it is taken from the "apify.json" file.

**Comment by remyoucef** [comment]
What about other variables like actor name and environment variables?

**Comment by mtrunkat** [comment]
Closing.
