### ISSUE TITLE
[feature] apify start actor-on-npm

### ISSUE THREAD

**Issue by pocesar** [apify/apify-cli#168]
I was thinking that maybe `apify start` could work like `npx`: `npx jest` downloads and installs jest in a temp folder and run on the current folder, for example. `apify start @apify/covid-brazil` would do the same: download everything, prepare the current folder for a local apify run and place the resulting dataset on the folder it was run from the console. this way, standalone actors could be released on npm. right now, you need to clone the repo, `npm install`, adjust the `apify_storage` `INPUT.json`, then `apify run` 

Think all covid actors, managed using lerna on the top of the repo, and releasing each one under the `@apify/covid-{country}` namespace, basically turning every actor like it was a cli program, one-off runs.

This would lead to increased visibility and will get a lot of attention from those websites that keep "watching" npm for interesting releases / keywords. it's a clean way for people to kickstart an actor locally without any hassle leveraging npm. it would accept a `INPUT.json` either by specifying `--input INPUT.json` or passing it curl style `-d '{}'`

this could also be available on the docs, on the tabs with code snippets on how to run Apify SDK "Run locally". so effectively it could be run using `npx apify-cli start` 😄

**Comment by mtrunkat** [comment]
Closing this for now as we don't plan to enable management of multi-repo actors soon. There are tools for that.
