### ISSUE TITLE
Binary files are corrupted when using "Multiple source files" upload

### ISSUE THREAD

**Issue by jakubjafra** [apify/apify-cli#169]
Hi! ✋Firstly I wanted to thank the Apify team for building such a useful tool for web scraping :)

I've been trying to use an external NPM package created by `npm pack` that produces `some-package-0.0.0.tgz`, using it in my `package.json` like:
```
{
  "dependencies": {
    "apify": "^0.20.3",
    "some-package": "file:some-package-0.0.0.tgz"
  }
}
```
File `some-package-0.0.0.tgz` was generated by npm and then copied to the Apify project folder. On my local machine, it worked fine, but not during the Apify build stage.

The contents of the folder were less than 3 MB so `apify push <id>` used "Multiple source files" upload. On build I got this kind of errors:
```
2020-05-02T11:00:40.169Z npm WARN tarball tarball data for some-package@file:some-package-0.0.0.tgz (sha512-yTZ3f6kKj55Nm1ww6k0FQ5+oIyvXMCRx0lLn6BBIAOuOmLITIG0elKjscyMITpo4h4aIl1jl1tUHGAlGsqcepA==) seems to be corrupted. Trying one more time.
2020-05-02T11:00:41.172Z npm WARN tarball tarball data for some-package@file:some-package-0.0.0.tgz (sha512-yTZ3f6kKj55Nm1ww6k0FQ5+oIyvXMCRx0lLn6BBIAOuOmLITIG0elKjscyMITpo4h4aIl1jl1tUHGAlGsqcepA==) seems to be corrupted. Trying one more time.
(... some bunch of errors ...)
2020-05-02T11:00:42.305Z npm ERR! Verification failed while extracting some-package@file:some-package-0.0.0.tgz:
2020-05-02T11:00:42.305Z npm ERR!
2020-05-02T11:00:42.306Z  Verification failed while extracting some-package@file:some-package-0.0.0.tgz:
2020-05-02T11:00:42.306Z npm ERR! Integrity check failed:
2020-05-02T11:00:42.307Z npm
2020-05-02T11:00:42.307Z  ERR!
(... integrities did not match ...)
```

I tried debugging the issue by creating custom `Dockerfile` and extracting the package manually (based on https://docs.apify.com/actor/source-code#custom-dockerfile):
```
FROM apify/actor-node-basic
COPY . ./
RUN apk add tar # thought the tar version might be an issue, it's alpine after all - but nope
RUN ls -al
RUN tar zxvf ./some-package-0.0.0.tgz
RUN ls -al && cd package
RUN npm install && npm list
```
But got some errors indicating the corrupted file:
```
2020-05-02T11:06:11.476Z Step 5/8 : RUN tar zxvf ./some-package-0.0.0.tgz
2020-05-02T11:06:11.592Z  ---> Running in b13674b121cd
2020-05-02T11:06:12.176Z gzip: invalid magic
2020-05-02T11:06:12.179Z
2020-05-02T11:06:12.180Z tar: Child returned status 1
2020-05-02T11:06:12.180Z tar: Error is not recoverable: exiting now
```
I've found out that `gzip: invalid magic` means that "gzip does not recognize your file as a gzip compressed file".

Strangely when I ran `docker build .` on my local machine, everything worked fine. That narrowed down the issue to Apify's way of uploading the project files. After the upload, I could open the `.tgz` on https://my.apify.com/ web preview and it showed as a binary file but in text format (there should be at least some info that I'm trying to view the binary file as a text?).

When I added some huge file to exceed 3MB "Multiple source files" upload's limit, then it created a zip file out of the folder and the build has passed successfully (just like on my local machine). I think there is a bug in a way that binary files are handled by "Multiple source files" upload, thus making them corrupted.

Also, I've noticed that if `.gitignore` the file is present in the same directory as I run Apify commands, then it uses its contents to exclude files - but without any indication of doing so. I've had problems with that approach, since I don't want to commit build artifacts to git, but I do want to get them uploaded to Apify. A short info message saying something like 
`Run: removing files ignored by .gitignore from deployment package` would save me some time. I could still have files ignored for git and pushed to Apify if I added them to `.gitignore` in a parent directory.

Feel free to ping me if you need any more details on the subject. Again, thanks for your work on the project :)

**Comment by drobnikj** [comment]
Hey @jakubjafra,

Thanks for the bug report.

it looks like more issue with UI code editor or backend of Apify API.
Do you have any actor on Apify where this happened?
It will help us with debugging.

**Comment by jakubjafra** [comment]
I think it's definitely an issue with the apify-cli uploader.

> Do you have any actor on Apify where this happened?
Yeah, actor ID is `ZiatcHQjFJ9Nzrn8n`. I use my solution with a dummy zip file to bring the package size over the limit, so the apify-cli uses zip in order to upload.

**Comment by remyoucef** [comment]
@drobnikj I think it related to #166 and is still occurs in the latest version (apify-cli/0.6.1 linux-x64 node-v12.16.1).

**Comment by mtrunkat** [comment]
This is most likely fixed at worker level build process. There was w wrong order of events. Please re-open if this is still happening.
