### ISSUE TITLE
[feature] Validate INPUT.json against INPUT_SCHEMA.json when testing locally

### ISSUE THREAD

**Issue by remyoucef** [apify/apify-cli#184]
It would be super helpful to add a command to validate the **INPUT.json** file against the **INPUT_SCHEMA.json** file.

This will help us avoid doing input validation via code when testing the actor locally.

Also, It allows validating the input before calling the actor on the platform (`apify call`).

**Comment by mtrunkat** [comment]
Closing in favor of #66 and we have command `apify vis` to validate input
