### ISSUE TITLE
login ok! but `apify create my-project` failed!

### ISSUE THREAD

**Issue by hero** [apify/apify-cli#193]
Hello, here are my test commands:
```bash
# test login [Ok]
$ apify login -t <my api TOKEN>
Success: You are logged in to Apify as ...

# test create project [Failed]
apify create my-first-prj
Error: connect ECONNREFUSED 0.0.0.0:443

# test create project with parameters [Failed]
$ apify create my-first-prj -t project_empty
Error: connect ECONNREFUSED 0.0.0.0:443

```

I guess some places can't access the template files：
https://github.com/apifytech/actor-templates/raw/master/templates/manifest.json

Why not bundle it with `afpfy-cli` tools together? 

Thx!

**Comment by tiandezhen** [comment]
The same issue

**Comment by metalwarrior665** [comment]
Thanks for the report. It was bundled in the apify-cli before but we factored it out because the templates are used in many places.

I'm reporting this to the team to find a solution.

**Comment by tiandezhen** [comment]
Suggest to publish it to an FTP server, a simple solution which can be done in minutes.

**Comment by tiandezhen** [comment]
And , in CLI codes the FTP server can be a backup trail when meeting Githup failure.

**Comment by mtrunkat** [comment]
Closing, please reopen if this is still happening
