### ISSUE TITLE
Internal server error during apify create

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-cli#250]
```
G:\www>apify create ctrip
Error: Response code 500 (Internal Server Error) 
```

We are calling Github API to fetch the source code of templates from Github. We use simple request, we probably need to add retries in case of 5xx errors.

**Comment by mtrunkat** [comment]
We could use `axios-retry` NPM package: https://github.com/apify/apify-status-page-tests/blob/main/src/tests/logs.js#L33
