### ISSUE TITLE
apify push pushes node_modules directory

### ISSUE THREAD

**Issue by jamesmurdza** [apify/apify-cli#261]
I'm not sure if this is intentional, however my local node_modules were uploaded and built into the Docker image, causing the actor to fail due to a difference in architectures.

**Comment by jamesmurdza** [comment]
Hi, the solution is here:

> One important thing to note is that you can use a .gitignore file to exclude files from being pushed. When you use apify push without a .gitignore, the full folder contents will be pushed, meaning that even the even apify_storage and node_modules will be pushed. These files are unnecessary to push, as they are both generated on the platform.
[Deploying with the Apify CLI](https://developers.apify.com/academy/apify-platform/deploying-your-code/deploying#with-apify-cli)

Just noting here that if there is any architecture difference this is not only _unnecessary_ but results in actor failure. So it may be worth considering to ignore these files anyways.

**Comment by mnmkng** [comment]
Yeah, ignoring node_modules when .gitignore is missing makes a lot of sense.

**Comment by mnmkng** [comment]
done here https://github.com/apify/apify-cli/pull/278
