### ISSUE TITLE
Use IS_APIFY_AT_HOME env var to check is actor runs locally

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-cli#270]
https://github.com/apify/apify-cli/blob/0cb0de4794ce2d78b84237d9612f88d9e4c6f2fa/src/lib/actor.js#L47

We should probably use IS_AT_HOME to check if we're running on Apify. When you run locally and you don't set the local storage env var, the above error shows. `apify run` sets this automatically, so it was a bit of a surprise, but we should still figure out a better way of managing this local/remote environment. The env vars are super confusing even for long time SDK users.

_Originally posted by @mnmkng in https://github.com/apify/apify-cli/issues/265#issuecomment-1080743802_

**Comment by B4nan** [comment]
@vladfrangu is this still valid? if so, we should also handle it before the v1 release
