### ISSUE TITLE
APIFY_MEMORY_MBYTES doesn't work

### ISSUE THREAD

**Issue by Keeyahto** [apify/apify-cli#274]
I am running a container with apify-cli on the docker server. The server is managed by an internal python script. I found that the variable APIFY_MEMORY_BYTES, which I gave a value to in apify.json before I built the container does not work. What should I do to make apify use more memory? APIFY_MEMORY_BYTES has a value of 4096. I also use puppeteer crawler so in theory the amount of memory should affect performance
![image](https://user-images.githubusercontent.com/57627790/180652181-2d5c1b3d-566e-4b88-bbfd-783cf32e9148.png)

**Comment by drobnikj** [comment]
You probably mean `APIFY_MEMORY_MBYTES`. You can check the [doc](https://sdk.apify.com/docs/guides/environment-variables#apify_memory_mbytes). Try to rename the env var and let me know if it helps.
