### ISSUE TITLE
Docker build fails when using Playwright Typescript template

### ISSUE THREAD

**Issue by gustavotr** [apify/apify-cli#280]
Steps to reproduce
- run `apify create my-actor`
- choose the Playwright typescript template
- try to build the docker image locally or on Apify platform

There is the erro I am getting:
![Screenshot_20220828_160313](https://user-images.githubusercontent.com/5346766/187075649-8b3a340c-e079-47e8-922a-2145f0dc2c08.png)

**Comment by B4nan** [comment]
TS 4.8 issue, same as https://github.com/apify/crawlee/issues/1494, pin your TS version to 4.7 till we resolve this please.

**Comment by gustavotr** [comment]
Worked
