### ISSUE TITLE
Should add storage to .gitignore if not already present

### ISSUE THREAD

**Issue by metalwarrior665** [apify/apify-cli#281]
It doesn't happen when using CLI for older projects

**Comment by B4nan** [comment]
> It doesn't happen when using CLI for older projects

What do you mean by this? I dont think we should alter any files if you just use the CLI to run the project. I can understand creating new projects, but for existing ones, not really.

**Comment by metalwarrior665** [comment]
The CLI already adds `apify_storage` to `.gitignore`, now we create a new `storage` folder which is committed if you are not careful. But I guess it is a minor thing and it will go away.

**Comment by B4nan** [comment]
Oh so you mean when creating new templates? If so it sounds valid and we should reopen.
