### ISSUE TITLE
Update push command to work with actor.json

### ISSUE THREAD

**Issue by novotnyj** [apify/apify-cli#287]
`apify push` should apply follwing from `.actor/actor.json`:
- `version`
- `buildTag`
- `environmentVariables`
- `title`
- `name`
- `description`

Also update `secrets` command - it stores secrets in `.apify` directory. It should work with `.actor` dir and `actor.json` file. Maybe create extra issue and PR for it.

**Comment by mhamas** [comment]
Close in favor of https://github.com/apify/apify-cli/issues/289
