### ISSUE TITLE
push also BODY(INPUT.json) from local

### ISSUE THREAD

**Issue by yonnyZer0** [apify/apify-cli#29]
It will be great if there will be possible by the command "apify push" to push also INPUT.json to Actor. There could be added a parameter to force it.

**Comment by mtrunkat** [comment]
@drobnikj check this one and possibly close

**Comment by drobnikj** [comment]
Closing this, as there is no need to have input sent on the Apify platform during the push.
1) You can use `apify call`, which takes local input and runs actor with it.
2) You can set up default or prefill values in INPUT_SCHEMA.json if default values are necessary in input on the platform.
