### ISSUE TITLE
Subcommands not to be separated by `:` but space instead

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-cli#309]
Based on the Apify Actors specification, the sub-commands should not be separated by `:` as:

```
apify secrets:add
apify actor:get-input
```

But by the space instead:

```
apify secrets add
apify actor get-input
```

This is a breaking change mainly for the secrets, as actor sub-commands are not used much. With this, we should consider if there is anything we should improve with the `apify secrets` command to beware of more breaking changes in the future.

**Comment by fnesveda** [comment]
We could do it backwards compatible and still support the old way of separation with `:` for the secrets command for a while (just not document it anywhere so new users don't use it anymore). We could remove it with some `1.0.0` release in the future.

**Comment by mnmkng** [comment]
Just FYI, it's a [config option of Oclif](https://oclif.io/docs/topic_separator#docsNav), so keeping it backwards compatible might require hacking it.

**Comment by B4nan** [comment]
It's time to revisit this, since we plan to release v1, we can do breaking changes. Do we want to try having both ways enabled in v1?

**Comment by mnmkng** [comment]
I'd go with just spaces.
