### ISSUE TITLE
Update docs v2 command reference during release

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-cli#348]
The [docs reference are outdated](https://github.com/apify/apify-cli/blob/master/docs/reference.md) because the commands reference gets updated just into readme during preparing release see https://github.com/apify/apify-cli/blob/master/CONTRIBUTING.md#publish-new-version

We need to ensure that the docs reference gets updated after release.

**Comment by fnesveda** [comment]
CC @B4nan
