### ISSUE TITLE
after push command it tries to open browser, causing pipeline fail

### ISSUE THREAD

**Issue by omortie** [apify/apify-cli#367]
`apify push` command after building successfully will try to open browser and ask user if you want to open browser or not. 
this is a new behavior and was not seen in older versions of the cli. it will cause the pipeline to fail because there is no option to disable this and also we can't send a 'n' (no) to the cli so it would not try and fail.

![image](https://github.com/apify/apify-cli/assets/114299877/979053d5-b689-41d9-a2f1-3494245cb370)

**Comment by B4nan** [comment]
This should be actually already fixed in master, we did that just yesterday, try latest beta version.

See #365, #366.
