### ISSUE TITLE
Branch protection breaks automatic docs CI script

### ISSUE THREAD

**Issue by barjin** [apify/apify-cli#378]
As seen [here](https://github.com/apify/apify-cli/actions/runs/5310475965/jobs/9612503069), the branch protection of the `master` branch breaks our CI script for automatic docs generation (it should automatically push the updated files into `master`, but it fails). 

The obvious (but maybe too crude) solution would be to give the CI script elevated permissions (can we do this on a file-to-file basis?)
An even cruder solution is to remove the push action - it's there "just" to keep the committed `package.json` in sync with the current latest `@apify/docs-theme` version. ~Since I cannot find the package in the package.json / shrinkwrap, it actually never worked(?)~

cc @B4nan

**Comment by B4nan** [comment]
Lets see if this helps:

<img width="753" alt="image" src="https://github.com/apify/apify-cli/assets/615580/c8bee1dd-7e9b-47ff-9350-5d5092ea5b74">

https://github.com/apify/apify-cli/actions/runs/5297304326/jobs/9635345795

**Comment by B4nan** [comment]
Right, I once again forgot there is a save button in the branch protection settings, it did help :]

https://github.com/apify/apify-cli/actions/runs/5297304326/jobs/9639338005
