### ISSUE TITLE
Cannot seem to apify actor:set-value anything

### ISSUE THREAD

**Issue by bwhitman** [apify/apify-cli#384]
I'm trying to set a local `startUrls` for testing a run before pushing it. I see the startUrls in `get-value`:

```
% apify actor:get-value INPUT
{
	"startUrls": [
		{
			"url": "URL HERE"
		}
	]
}
```

But setting it (to anything) does not work for me. 

```
% apify actor:set-value INPUT "{'startUrls':[{'url':'NEW URL'}]}"
Error: Cannot set properties of undefined (setting 'flagsUsed')
```

I've re-read the docs many times and thought this should work. I think it's a bug? Or it could be an issue of documentation. (I can't seem to set any key, let alone `INPUT`.)

**Comment by B4nan** [comment]
cc @drobnikj, I'd guess this comes from the telemetry PR? #362
