### ISSUE TITLE
Enhance help and doc of `apify init` command for Scrapy wrapping functionality

### ISSUE THREAD

**Issue by vdusek** [apify/apify-cli#490]
Request from Slack by Jan Curn:

> Hey, I noticed the Apify CLI command apify init doesn't say anything about the Scrapy wrapping functionality. Please can you add some info to both the help and docs?

Help of `apify init`: https://docs.apify.com/cli/docs/reference#apify-init-actorname

**Comment by jancurn** [comment]
Fixed in https://github.com/apify/apify-cli/pull/494

**Comment by jancurn** [comment]
-
