### ISSUE TITLE
apify push and call do not validate whether they are in an Actor folder

### ISSUE THREAD

**Issue by tobice** [apify/apify-cli#551]
### How to reproduce:

```
$ mkdir test-folder
$ cd test-folder
$ apify push
$ apify call
```
### Expected behavior:

`apify push` fails telling me that the current folder is not a valid Actor folder (as it's completely empty!). `apify call` does the same.

### Actual behavior:

`apify push` pushes an empty Actor.

`apify call` fails with:

```
Error: Cannot find actor with ID 'tobice/undefined' in your account. Call "apify push" to push this actor to Apify platform.
```

### CLI Version: 

` apify-cli/0.19.4 linux-x64 node-v18.19.0`

**Comment by vladfrangu** [comment]
Btw, this has been fixed in apify-cli@beta. Keeping this issue open till release

**Comment by vladfrangu** [comment]
Actually will close this so it's visible as done on the milestone :D

**Comment by tobice** [comment]
Awesome to hear :heart:
