### ISSUE TITLE
Version 0.20.0 installed via NPM fails to work

### ISSUE THREAD

**Issue by cliftonmcintosh** [apify/apify-cli#587]
When I install the latest version of apify-cli via npm and try to run it, I get an error. I cannot login or even get the version number. Another person in my organization experiences the same issue, and we are also experiencing this issue in our continuous integration runs.

Downgrading to 0.19.5 solves the problem.

### Sample output

```
clifton.mcintosh@_:~/code/apify
$ npm install -g apify-cli@latest
...
clifton.mcintosh@_:~/code/apify
$ apify --version
Error: undefined
clifton.mcintosh@_:~/code/apify
$ apify login -t apify_api_...my_token
Error: undefined
```

### System details
NodeJS version installed using ASDF: 16.13.0
MacOS version: 14.5
Chip: M1 Max

**Comment by cliftonmcintosh** [comment]
Ahh. I see it's a feature

> feat: prevent old node from running CLI by @vladfrangu in https://github.com/apify/apify-cli/pull/522

**Comment by vladfrangu** [comment]
That error looks super wrong tho, not how it was supposed to look like. What node version are you running?

**Comment by vladfrangu** [comment]
Oh, nice catch, ty! That's a bug on our side too for not showing it right, thanks for reporting this. I'll reopen it for tracking purposes
