### ISSUE TITLE
`apify create` cannot create project in a folder with space in path

### ISSUE THREAD

**Issue by bornedan** [apify/apify-cli#692]
**Problem description**: The `apify create my-actor -t python-playwright` command fails to create a project in a folder with spaces in its path. When running this command in a directory with a space in the path, the following error occurs.

**Example**:

Working directory path: `c:\Data\Personal projects\Apify`

**Steps to reproduce**:
1. Open `cmd.exe` on Windows 11.
2. Navigate to a folder with a space in its path (e.g., `c:\Data\Personal projects\Apify`).
3. Run the command: `apify create my-actor -t python-playwright`.

**Error message**:
```
c:\Data\Personal projects\Apify>apify create my-actor -t python-playwright
Info: Python version 3.11.9 detected.
Info: Creating a virtual environment in "c:\Data\Personal projects\Apify\my-actor\.venv" and installing dependencies from "requirements.txt"...
Run: python -m venv --prompt . .venv
Run: c:\Data\Personal projects\Apify\my-actor\.venv\Scripts\python.exe -m pip install --no-cache-dir --no-warn-script-location --upgrade pip setuptools wheel
'c:\Data\Personal' is not recognized as an internal or external command,
operable program or batch file.
    Error: c:\Data\Personal projects\Apify\my-actor\.venv\Scripts\python.exe exited with code 1
```

**Additional information**:
- When I run this command in a folder *without* spaces in the path, it works correctly.
- **System**: Windows 11
- **Command Line**: cmd.exe
- **Apify version**: `apify-cli/0.20.11 win32-x64 node-v22.11.0`

**Comment by vladfrangu** [comment]
0.20.13 is being released with a fix for this! 🫡
