### ISSUE TITLE
apify init should only add apify_storage if not already present to .gitignore file

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-cli#72]

**Comment by vladyslav-n** [comment]
Totally agree! Adding apify_storage  to .gitignore each time with `apify init` usually creates changes to .gitignore that you didn't intend to commit and it is very annoying(

**Comment by mtrunkat** [comment]
@drobnikj

**Comment by drobnikj** [comment]
It is more bug than enhancement, the fix should be simple simple.

**Comment by metalwarrior665** [comment]
Yes please, me and other devs are still manually deleting that :)
