### ISSUE TITLE
Add check for security vulnerability with badge to readme

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-cli#86]
Use third party vulnerability DB and tool like [snyk](https://snyk.io/test/npm/apify-cli/0.3.3)
[![Known Vulnerabilities](https://snyk.io/test/npm/apify-cli/0.3.3/badge.svg)](https://snyk.io/test/npm/apify-cli/0.3.3)

**Comment by mnmkng** [comment]
I think GitHub now does this automatically.

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/128010875-0e9364ab-ca80-430b-a3c8-574754771fb3.png)

**Comment by B4nan** [comment]
both snyk and npm audit are pure bullshit and plague to all open source projects

https://overreacted.io/npm-audit-broken-by-design/

**Comment by szmarczak** [comment]
I haven't looked deeper into the report, but some other reports on other packages are legit.

`npm` is not aware of the context. It doesn't know the purpose of the function.
It assumes *anything* can trigger it, so it looks for nitpicks as well. I agree, it's quite annoying.

I remember when snyk reported a vuln for a CLI that was executing other processes :P

**Comment by B4nan** [comment]
yeah the idea itself is good, the implementation is terrible, it spams so hard that most of the maintainers will simply ignore it. it is very hard to find a valid suggestion/report when it is burried among hundreds of invalid ones. 

on the other hand, it may have a positive effect - to force others to reduce number of dependencies, especially those unmaintained :]
