### ISSUE TITLE
Schema validation command improvements

### ISSUE THREAD

**Issue by jancurn** [apify/apify-cli#92]
`apify vis` command should have a better name, e.g. `validate-schema`. See `git help -g` how to name commands.

Also, we should run the validation automatically when calling `apify push`.

**Comment by B4nan** [comment]
Since we are preparing v1, its time to more forward with this (if we still want to).

Or we could support both.

**Comment by jancurn** [comment]
yes please! let's use `validate-schema` by default, and `vis` only for backwards compatibility (or maybe drop completely? is anybody using it?)

**Comment by B4nan** [comment]
We use it in the WCC (via CI checks), I guess there will be more people aware of it in Apify, not sure about 3rd party users.

I don't mind a rename, if we keep it backward compatible, we should still deprecate the `vis` variant and print a warning when it's used.

**Comment by jancurn** [comment]
Yeah, makes sense to keep & deprecate.
