### ISSUE TITLE
Apify run should allow starting different npm scripts or files for testing

### ISSUE THREAD

**Issue by metalwarrior665** [apify/apify-cli#95]
Right now, I have to change `npm start` script if I want to test with all the ENV injected.

We should allow either start from any file or with different npm scripts.

**Comment by drobnikj** [comment]
I would be nice that we can use env vars for debugging. I try to find a way how we can do it.

**Comment by bernardro** [comment]
As a workaround, if you are debugging in an IDE like Webstorm, you can still get the environment variables injected during debug/run session by adding `apify run` as shown below and then create a *npm* run configuration for it.

![apify_run](https://user-images.githubusercontent.com/53663510/69277480-58305900-0bae-11ea-9233-ca1799849d33.png)

When you start the debug session the environment variables will be injected from apify secrets - assuming you have set up the environment variables in apify.json like this:
```
{   
    ...
    "env": {
        "SECRET_KEY": "@secretStoredWithApifySecretsAdd"
        "API_KEY": "slksAS3asf23slffeflse"
    }
    ...
}
```

**Comment by vladfrangu** [comment]
Its already out in beta! If you want, I can ping you once its out in stable too
